name: selenium4-java-ja

on:
  pull_request:
  schedule:
    - cron: '42 18 * * *'

jobs:
  test:
    strategy:
      matrix:
        base-url: ["https://hotel-example-site.takeyaqa.dev/ja", "https://hotel.testplanisphere.dev/ja"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build with Gradle Wrapper
      run: ./gradlew test
      env:
        BASE_URL: ${{ matrix.base-url }}
